@echo off
setlocal

call "%AIMONITOR_VSDEVCMD%" -no_logo -arch=%AIMONITOR_VS_ARCH% -host_arch=%AIMONITOR_VS_ARCH%
if errorlevel 1 exit /b %ERRORLEVEL%

cd /d "%AIMONITOR_DESKTOP_ROOT%"
"%AIMONITOR_NODE_EXECUTABLE%" "%AIMONITOR_TAURI_SCRIPT%" %AIMONITOR_TAURI_MODE%
exit /b %ERRORLEVEL%
